#!/usr/bin/env python3
"""Make /manifest.json describe Hive rather than Open WebUI.

/manifest.json is generated by the backend, not served from STATIC_DIR, so it
cannot be fixed by dropping a file into owui-static. Its name and short_name
already follow WEBUI_NAME; three other fields did not:

  1. description was Open WebUI's own sentence about itself, with WEBUI_NAME
     substituted in, so it asserted that sentence about Hive. Replaced with
     Hive's own product description from https://scubed.co/hive, kept
     name-driven so a renamed deployment still reads correctly.
  2. background_color was '#343541', a colour from neither brand. Now the
     charcoal Hive publishes, and a matching theme_color is added, which
     upstream omits entirely.
  3. Both icon entries pointed at logo.png, including the one declared
     `maskable`. A maskable icon is cropped to a circle by the platform, and
     logo.png is a rounded square whose corners that crop cuts off. The
     maskable entry now points at the full-bleed web-app-manifest assets that
     generate-brand-assets.py renders with a wider safe margin for exactly this.

This is the single source of truth for the manifest. There is deliberately no
second manifest file: upstream ships an unreferenced static/site.webmanifest,
and shipping our own copy of it would leave two manifests disagreeing, with the
one the shell actually links being the only one that counts.

Every replacement asserts it matched, so a digest bump whose upstream source
shifted fails the build instead of silently restoring vendor branding.
"""

from __future__ import annotations

import ast
import pathlib
import sys

MAIN = pathlib.Path("/app/backend/open_webui/main.py")

DESCRIPTION_OLD = (
    "'description': f'{app.state.WEBUI_NAME} is an open, extensible, "
    "user-friendly interface for AI that adapts to your workflow.',"
)
DESCRIPTION_NEW = (
    "'description': f'{app.state.WEBUI_NAME} is a sovereign AI system: "
    "assistant, coding, and knowledge work AI that runs entirely inside your "
    "own infrastructure, under your own keys.',"
)

ICONS_OLD = """            'background_color': '#343541',
            'icons': [
                {
                    'src': '/static/logo.png',
                    'type': 'image/png',
                    'sizes': '500x500',
                    'purpose': 'any',
                },
                {
                    'src': '/static/logo.png',
                    'type': 'image/png',
                    'sizes': '500x500',
                    'purpose': 'maskable',
                },
            ],"""

ICONS_NEW = """            'background_color': '#2b2b28',
            'theme_color': '#2b2b28',
            'icons': [
                {
                    'src': '/static/logo.png',
                    'type': 'image/png',
                    'sizes': '500x500',
                    'purpose': 'any',
                },
                {
                    'src': '/static/web-app-manifest-192x192.png',
                    'type': 'image/png',
                    'sizes': '192x192',
                    'purpose': 'maskable',
                },
                {
                    'src': '/static/web-app-manifest-512x512.png',
                    'type': 'image/png',
                    'sizes': '512x512',
                    'purpose': 'maskable',
                },
            ],"""


def main() -> None:
    src = MAIN.read_text()

    for label, old, new in (
        ("manifest description", DESCRIPTION_OLD, DESCRIPTION_NEW),
        ("manifest colours and icons", ICONS_OLD, ICONS_NEW),
    ):
        hits = src.count(old)
        if hits != 1:
            print(f"hive manifest patch: expected 1 site for {label}, found {hits}", file=sys.stderr)
            raise SystemExit(1)
        src = src.replace(old, new)

    MAIN.write_text(src)

    # Read back rather than trust the write, same posture as the other patches.
    after = MAIN.read_text()
    assert "open, extensible, user-friendly" not in after, "vendor description survived"
    assert "'#343541'" not in after, "vendor background colour survived"
    assert "web-app-manifest-512x512.png" in after, "maskable icon not wired"
    ast.parse(after)
    print("hive manifest patch: description, colours and maskable icons rewritten")


if __name__ == "__main__":
    main()
