#!/usr/bin/env bash
# Live proof for the chat-origin admin lockdown (#736, #948, #949).
#
# Runs the repo's own compose definitions in an isolated project against an
# image built from this branch, then, holding a real Open WebUI ADMIN session,
# probes the public chat origin and the container's own loopback side by side.
# The pairing is the point: a 404 from the origin next to a 200 from inside the
# container is the proxy refusing a request Open WebUI would have served.
#
# No real credential exists anywhere in this stack (see proof.env), and no
# response body is printed: only status codes and booleans naming which secret
# FIELDS a body carried.
set -uo pipefail

HERE=$(cd -- "$(dirname -- "$0")" && pwd)
REPO=$(cd -- "$HERE/../../.." && pwd)
# Stack inputs (the throwaway env file and the port/image override) stay out of
# the repository: proof.env holds placeholder values for variables that carry
# real credentials on a deployment, and nothing that shape belongs in git.
SP=${PROOF_STACK_DIR:?set PROOF_STACK_DIR to the directory holding proof.env and proof-override.yml}
PROJECT=adminlock736
PORT=3079
OUT=$SP/live-proof.log
FLAGS="--env-file $SP/proof.env -f docker-compose.yml -f $SP/proof-override.yml --profile local --profile chat"

cd "$REPO/deploy/docker"
compose() { docker compose -p "$PROJECT" $FLAGS "$@"; }

say() { printf '%s\n' "$*" | tee -a "$OUT"; }

: > "$OUT"
say "# Live proof: chat origin admin lockdown (#736, #948, #949)"
say "# stack: isolated compose project '$PROJECT', image hive-owui-adminlock:after"
say "#        built from branch fix/chat-origin-admin-lockdown"
say "# public origin under test: http://localhost:$PORT (caddy-owui, this branch's Caddyfile.owui)"
say "# in-container comparison:  http://127.0.0.1:8080 inside the open-webui container"
say "# placeholders only: no real gateway key, OAuth secret or password exists in this stack"
say ""

# open-webui first, then caddy-owui once it is healthy. caddy-owui declares
# `depends_on: open-webui: service_healthy`, and --no-deps does not waive that
# for a service named on the same command line, so starting both at once fails
# the whole `up` while open-webui is still booting.
compose up -d --no-deps open-webui >> "$OUT" 2>&1
for _ in $(seq 1 120); do
  state=$(compose ps --format '{{.Service}} {{.Health}}' | awk '$1=="open-webui"{print $2}')
  [ "$state" = "healthy" ] && break
  sleep 2
done
compose up -d --no-deps caddy-owui >> "$OUT" 2>&1
for _ in $(seq 1 60); do
  if curl -fsS -o /dev/null "http://127.0.0.1:$PORT/health" 2>/dev/null; then break; fi
  sleep 2
done
say "## stack up"
compose ps --format '{{.Service}}\t{{.Status}}' | tee -a "$OUT"
say ""

say "## admin session"
# WEBUI_SECRET_KEY is generated by the server's own start.sh into the server
# PROCESS environment, so an `exec` does not inherit it and importing
# open_webui.env without one aborts. The bootstrap signs nothing, it only
# writes two rows, so any value does. The token minted below reads the REAL
# key out of /proc, which is what scripts/owui-mint-admin-token.py exists to do.
uid=$(compose exec -T -e WEBUI_SECRET_KEY=proof-bootstrap-only open-webui \
  python3 - < "$HERE/bootstrap-admin.py" 2>>"$OUT" | tr -d '\r')
say "proof admin user id: ${uid:0:8}... (throwaway account, isolated stack)"
token=$(compose exec -T open-webui python3 - \
  < "$REPO/scripts/owui-mint-admin-token.py" 2>>"$OUT" | tr -d '\r')
if [ -z "$token" ]; then say "FAILED to mint an admin session token"; exit 1; fi
say "minted a five minute Open WebUI admin session (scripts/owui-mint-admin-token.py), value not printed"
role=$(curl -s -H "Authorization: Bearer $token" "http://127.0.0.1:$PORT/api/v1/auths/" \
  | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d.get("role"), d.get("email"))')
say "session role as reported by Open WebUI itself: $role"
say ""

# --- probes -------------------------------------------------------------
origin_probe() {
  local method=$1 path=$2 body=${3:-}
  local code
  code=$(curl -s -o /tmp/proof-body.json -w '%{http_code}' -X "$method" \
    -H "Authorization: Bearer $token" -H 'Content-Type: application/json' \
    ${body:+-d "$body"} "http://127.0.0.1:$PORT$path")
  printf '%-6s %-52s origin=%s\n' "$method" "$path" "$code" | tee -a "$OUT"
}

inside_probe() {
  local method=$1 path=$2 body=${3:-}
  local out
  out=$(compose exec -T -e T="$token" open-webui python3 - "$method" "$path" "${body:-}" <<'PY' 2>>"$OUT"
import json, os, sys, urllib.request, urllib.error
method, path, body = sys.argv[1], sys.argv[2], sys.argv[3]
data = body.encode() if body else None
req = urllib.request.Request(
    f"http://127.0.0.1:8080{path}", data=data, method=method,
    headers={"Authorization": f"Bearer {os.environ['T']}",
             "Content-Type": "application/json"},
)
try:
    with urllib.request.urlopen(req, timeout=30) as r:
        status, raw = r.status, r.read().decode()
except urllib.error.HTTPError as e:
    status, raw = e.code, e.read().decode()
# Never print a body. Report only which secret-bearing FIELD NAMES it carried.
fields = []
try:
    parsed = json.loads(raw)
except Exception:
    parsed = None
def walk(node, prefix=""):
    if isinstance(node, dict):
        for k, v in node.items():
            key = f"{prefix}{k}"
            if any(s in k.lower() for s in ("secret", "api_key", "key")) and isinstance(v, str) and v:
                fields.append(key)
            walk(v, key + ".")
    elif isinstance(node, list):
        for item in node:
            walk(item, prefix)
walk(parsed)
print(json.dumps({"status": status, "secret_fields_present": sorted(set(fields))[:6]}))
PY
)
  printf '%-6s %-52s inside=%s\n' "$method" "$path" "$out" | tee -a "$OUT"
}

say "## 1. #736: the Functions API, which installs and enables plugin code"
say "#     inside the container that holds PGVECTOR_DB_URL and OWUI_SHIM_KEY."
origin_probe POST /api/v1/functions/create '{"id":"probe","name":"probe","content":"","meta":{}}'
origin_probe POST /api/v1/functions/id/hive_jwt_forward/update '{}'
origin_probe POST /api/v1/functions/id/hive_jwt_forward/toggle
origin_probe POST /api/v1/functions/id/hive_jwt_forward/toggle/global
origin_probe DELETE /api/v1/functions/id/hive_jwt_forward/delete
say "#     Same admin session, same path, from inside the container: served."
inside_probe GET /api/v1/functions/
say ""

say "## 2. #948: the two routes that return the gateway key and oauth.client_secret"
origin_probe GET /api/v1/configs/namespace/oauth
origin_probe GET /api/v1/configs/namespace/rag
origin_probe POST /api/v1/configs/import '{"config":{}}'
origin_probe GET /api/v1/configs/export
say "#     From inside the container the same admin session still reaches them,"
say "#     which is what makes the 404s above the proxy's answer and not a 401."
inside_probe GET /api/v1/configs/namespace/oauth
inside_probe GET /api/v1/configs/namespace/rag
say ""

say "## 3. The chat product on the same origin, same session"
origin_probe GET /api/config
origin_probe GET /api/v1/configs/banners
origin_probe GET /api/v1/models/list
origin_probe POST /api/v1/users/user/settings/update '{"ui":{}}'
origin_probe POST /api/v1/functions/id/hive_jwt_forward/valves/user/update '{}'
say ""

say "## 4. #736's install, rerouted: scripts/install-owui-jwt-forward-in-container.sh"
say "#     (the reroute is what made blocking the paths above possible)"
HIVE_COMPOSE_FLAGS="-p $PROJECT $FLAGS" OWUI_ADMIN_TOKEN="$token" \
  "$REPO/scripts/install-owui-jwt-forward-in-container.sh" >> "$OUT" 2>&1
install_rc=$?
say "wrapper exit code: $install_rc"
tail -6 "$OUT" | grep -E "hive_jwt_forward|Error|error" | tee -a "$OUT" >/dev/null
say "#     End state read back out of the API, inside the container:"
inside_probe GET /api/v1/functions/id/hive_jwt_forward
state=$(compose exec -T -e T="$token" open-webui python3 - <<'PY' 2>>"$OUT"
import json, os, urllib.request
req = urllib.request.Request(
    "http://127.0.0.1:8080/api/v1/functions/id/hive_jwt_forward",
    headers={"Authorization": f"Bearer {os.environ['T']}"},
)
with urllib.request.urlopen(req, timeout=30) as r:
    d = json.load(r)
print(json.dumps({k: d.get(k) for k in ("id", "name", "type", "is_active", "is_global")}))
PY
)
say "installed function: $state"
say ""
say "# stack left running for the screenshot pass; torn down at the end of the proof run."
