#!/usr/bin/env bash
# check-retention-schedule.sh -- Fail unless the nightly metering retention job
# is scheduled, pointed at the right procedure, and actually running, on the
# database this stack uses.
#
# Why this exists (issue #645)
# ---------------------------
# 20260729_02_metering_shadow_verdicts_retention.sql sets the purge job up in
# two guarded blocks: one creates the pg_cron extension when
# pg_available_extensions lists it, and a later one calls cron.schedule only
# when pg_extension shows pg_cron installed. Each guard degrades to a RAISE
# NOTICE, so a host without the extension gets no nightly retention at all and
# the only evidence is a line in a job log nobody rereads after the run goes
# green.
#
# Why it changed from a report into a gate
# ---------------------------------------
# The report-only version of this script was worse than nothing, and the reason
# is worth keeping: it printed "Nightly metering retention is scheduled and
# active" for weeks while the self-hosted database had no pg_cron and no job.
# It was not lying about the row it read. It was reading the HOSTED Supabase
# project, which preloads pg_cron, because the migrate job's connection came
# from a separate secret set rather than from the value the stack connects
# with. Two independent defects produced one confident green:
#
#   1. Nothing tied the connection to the database the application uses, so a
#      true answer about the wrong cluster read as a true answer.
#   2. Absence was a ::warning::, which does not fail anything, and a warning
#      on a green run is indistinguishable from no warning to everyone who
#      reads run conclusions rather than logs.
#
# Both halves are closed here:
#
#   * HIVE_EXPECTED_DB_CLUSTER is REQUIRED, and this script compares it against
#     pg_control_system().system_identifier over its own connection. That value
#     is generated by initdb and is unique per cluster. The deploy workflow
#     sets it from what the running supabase-db CONTAINER reports, over a route
#     and from an input unrelated to this script's connection, so pointing this
#     script at any other database fails instead of reporting on it. Unset is
#     a failure too: a check that cannot say which database it read has not
#     checked anything.
#   * Every negative verdict exits non-zero. Absence, a job that is inactive, a
#     job whose command no longer calls the purge procedure, a job registered
#     against another database, a job whose last run failed, and a job with no
#     successful run in the last 72 hours are all failures.
#
# The last one is the point of the whole rewrite. "A row exists in cron.job" is
# the same false green in a new costume: a job that errors every night, or one
# whose background worker is not running because pg_cron is installed but not
# preloaded, looks perfect in cron.job and does nothing. So the verdict is
# evidence of EXECUTION, read from cron.job_run_details.
#
# Why 72 hours and not 26. The schedule is daily, so 26 hours would be the
# tight bound. It is deliberately loose instead: a box reboot across 21:00 UTC
# makes pg_cron skip that night through no fault of the schedule, and a check
# that blocks deploys over one skipped night is a check somebody switches off.
# Three nights of silence costs nothing against a 90-day retention window, and
# a genuinely dead job is caught on the third day at the latest. A single
# failed run is caught immediately and separately, without waiting out the
# window.
#
# Exit status
# -----------
# 0 only when retention is scheduled, correctly aimed, and has succeeded within
# the window. Anything else is 1, including "could not tell", which fails the
# migrate job and stops the deploy. That coupling is intended: an unscheduled
# retention job on this database was invisible for weeks precisely because
# nothing it broke was ever load bearing enough to notice.
#
# Connection settings come from libpq environment variables (PGHOST, PGPORT,
# PGUSER, PGDATABASE, PGPASSWORD), same as apply-migrations.sh. No DSN is built
# here, because DSN parameters are per driver and psql is a libpq client.
#
# PSQL_BIN names the client, same as apply-migrations.sh, and for the same
# reason: on the demo box the database has no published port and only exists
# inside the stack's compose network, so the caller points this at
# scripts/stack-psql.sh.

set -euo pipefail

JOB_NAME='metering-shadow-verdicts-purge'
# Kept as a literal, not an environment knob. A knob here is a way to make this
# check pass without making retention work, which is the failure this file is a
# response to.
MAX_SUCCESS_AGE='72 hours'

PSQL_BIN="${PSQL_BIN:-psql}"

psql_q() { "$PSQL_BIN" --no-psqlrc -qtAX -v ON_ERROR_STOP=1 "$@"; }

# ---------------------------------------------------------------------------
# Which database is this?
# ---------------------------------------------------------------------------
if [ -z "${HIVE_EXPECTED_DB_CLUSTER:-}" ]; then
  echo "::error::HIVE_EXPECTED_DB_CLUSTER is not set, so this check cannot prove which database it is reading. Refusing to report on retention: the previous version of this check reported a healthy schedule for weeks while connected to a different cluster. Set it to the system_identifier of the database the stack runs (the deploy workflow reads that from the supabase-db container)."
  exit 1
fi

if ! actual_cluster="$(psql_q -c 'SELECT system_identifier FROM pg_control_system()')"; then
  echo "::error::could not open a connection to check retention, so the state of nightly metering retention is unknown. Unknown is not healthy."
  exit 1
fi
actual_cluster="$(printf '%s' "$actual_cluster" | tr -d '[:space:]')"
if [ -z "$actual_cluster" ]; then
  echo "::error::the retention connection returned no system_identifier, so the database being checked could not be identified at all."
  exit 1
fi
if [ "$actual_cluster" != "$HIVE_EXPECTED_DB_CLUSTER" ]; then
  echo "::error::retention check is connected to cluster $actual_cluster but the stack's database is cluster $HIVE_EXPECTED_DB_CLUSTER. Refusing to report retention health for a database the application does not use. This is the exact shape of the defect that hid an unscheduled retention job for weeks."
  exit 1
fi

# ---------------------------------------------------------------------------
# Is pg_cron even installed?
# ---------------------------------------------------------------------------
# Checked separately and first: when pg_cron is not installed the cron schema
# does not exist either, and a single query mentioning cron.job would fail to
# parse rather than returning a verdict, no matter how the CASE is arranged.
if ! extension_present="$(psql_q -c "SELECT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron')")"; then
  echo "::error::the pg_cron extension query failed, so whether nightly metering retention is scheduled is unknown. Unknown is not healthy."
  exit 1
fi

if [ "$extension_present" != "t" ]; then
  echo "::error::Nightly metering retention is NOT scheduled: the pg_cron extension is not installed on cluster $actual_cluster, so the retention migrations skipped cron.schedule and public.metering_shadow_verdicts will grow without bound. This deployment ships pg_cron in its own database image (deploy/docker/Dockerfile.supabase-db) and preloads it via the supabase-db command in docker-compose.enterprise.yml, so an absent extension means the container is running an older image or a different command. Recreate supabase-db from the current compose definition."
  exit 1
fi

# ---------------------------------------------------------------------------
# Is it scheduled, aimed correctly, and running?
# ---------------------------------------------------------------------------
# One query, one verdict, "CODE|detail". Reached only when pg_cron is installed,
# so cron.job and cron.job_run_details are guaranteed to resolve.
verdict_sql="
WITH j AS (
  SELECT jobid, active, command, schedule, database
  FROM cron.job
  WHERE jobname = '$JOB_NAME'
),
terminal AS (
  SELECT d.status, coalesce(d.end_time, d.start_time) AS at
  FROM cron.job_run_details d
  JOIN j ON j.jobid = d.jobid
  WHERE d.status IN ('succeeded', 'failed')
  ORDER BY d.start_time DESC
  LIMIT 1
),
ok_run AS (
  SELECT max(coalesce(d.end_time, d.start_time)) AS at
  FROM cron.job_run_details d
  JOIN j ON j.jobid = d.jobid
  WHERE d.status = 'succeeded'
)
SELECT CASE
  WHEN NOT EXISTS (SELECT 1 FROM j)
    THEN 'SCHEDULE_MISSING|no job named $JOB_NAME exists'
  WHEN NOT EXISTS (SELECT 1 FROM j WHERE active)
    THEN 'SCHEDULE_INACTIVE|the job exists but active is false'
  WHEN NOT EXISTS (SELECT 1 FROM j WHERE command LIKE '%purge_metering_shadow_verdicts%')
    THEN 'SCHEDULE_HOLLOW|its command does not call the purge procedure: ' || (SELECT command FROM j LIMIT 1)
  WHEN NOT EXISTS (SELECT 1 FROM j WHERE database = current_database())
    THEN 'SCHEDULE_WRONG_DB|it is registered against database ' || (SELECT database FROM j LIMIT 1) || ', not ' || current_database()
  WHEN (SELECT at FROM ok_run) IS NULL
    THEN 'NEVER_SUCCEEDED|' || coalesce((SELECT 'the most recent finished run ' || status || ' at ' || at FROM terminal), 'no run has ever been recorded') || ' (cron.log_run=' || coalesce(current_setting('cron.log_run', true), 'unset') || ')'
  WHEN (SELECT at FROM ok_run) < now() - interval '$MAX_SUCCESS_AGE'
    THEN 'STALE|last succeeded at ' || (SELECT at FROM ok_run)
  WHEN (SELECT status FROM terminal) <> 'succeeded'
    THEN 'LAST_RUN_FAILED|the most recent finished run ' || (SELECT status || ' at ' || at FROM terminal)
  ELSE 'OK|schedule ' || (SELECT schedule FROM j LIMIT 1) || ', last succeeded at ' || (SELECT at FROM ok_run)
END"

if ! verdict="$(psql_q -c "$verdict_sql")"; then
  echo "::error::pg_cron is installed but the cron.job / cron.job_run_details query failed, so whether nightly metering retention runs is unknown. Unknown is not healthy."
  exit 1
fi

code="${verdict%%|*}"
detail="${verdict#*|}"

case "$code" in
  OK)
    echo "::notice::Nightly metering retention is scheduled, active and executing on cluster $actual_cluster ('$JOB_NAME', $detail)."
    exit 0
    ;;
  SCHEDULE_MISSING|SCHEDULE_INACTIVE|SCHEDULE_HOLLOW|SCHEDULE_WRONG_DB)
    echo "::error::Nightly metering retention is NOT scheduled on cluster $actual_cluster: $detail. public.metering_shadow_verdicts will grow without bound. supabase/migrations/20260822_01_metering_retention_pg_cron_schedule.sql is what creates this job."
    exit 1
    ;;
  NEVER_SUCCEEDED)
    echo "::error::Nightly metering retention is scheduled on cluster $actual_cluster but has never completed successfully: $detail. A job row that never executes is the same as no retention at all. If pg_cron is installed without being in shared_preload_libraries its background worker never starts and every run is invisible (issue #615); check the supabase-db command in docker-compose.enterprise.yml."
    exit 1
    ;;
  STALE)
    echo "::error::Nightly metering retention has not succeeded in the last $MAX_SUCCESS_AGE on cluster $actual_cluster: $detail. The job is registered but is no longer running, so public.metering_shadow_verdicts is growing without bound."
    exit 1
    ;;
  LAST_RUN_FAILED)
    echo "::error::The nightly metering retention job on cluster $actual_cluster failed on its last run: $detail. Read the return_message column of cron.job_run_details for that jobid."
    exit 1
    ;;
  *)
    echo "::error::unexpected retention verdict '$verdict' for '$JOB_NAME' on cluster $actual_cluster, so retention state is unknown. Unknown is not healthy."
    exit 1
    ;;
esac
