#!/usr/bin/env python3
"""Mint a short-lived Open WebUI admin session token. Prints it on stdout.

Issue #556. Installing the hive_jwt_forward Function needs an Open WebUI admin
session, and a deploy has no way to obtain one the normal way:

  * ENABLE_ADMIN_PANEL is "false" on the demo box, and deploy/docker/
    Caddyfile.owui answers 404 on /api/v1/auths/signin, so no password sign-in
    is reachable even if a local password were known. Open WebUI gives every
    OAuth-provisioned account a random password it never discloses, and
    ENABLE_SIGNUP is "false", so there is no account to sign in as.
  * The OAuth journey that CI uses needs a browser: Supabase authorize, the
    web-console consent page, then the callback. A deploy step has none.
  * Inventing a dedicated admin account, or parking a long-lived admin bearer
    token in the box's .env, both add a standing credential that has to be
    rotated and can silently expire. A fresh Enterprise deployment would not
    have one at all, which is exactly the gap #556 is about.

So this mints one instead, from inside the open-webui container, for an admin
account that already exists. It creates nothing, changes nothing, and the token
it prints expires in five minutes.

Run it INSIDE the container, because both inputs live there:

  docker compose exec -T open-webui python3 - < scripts/owui-mint-admin-token.py

Both inputs are read from the running server's own process environment rather
than assumed, since neither is declared in docker-compose.yml:

  * WEBUI_SECRET_KEY is generated by Open WebUI's backend/start.sh into
    .webui_secret_key and exported only into the server process it execs. A
    `docker compose exec` shell does NOT inherit it, and open_webui.env would
    fall back to a different value, producing a token the server rejects. So
    the real value is read out of /proc/<pid>/environ.
  * DATABASE_URL is unset in this deployment, so Open WebUI defaults to
    sqlite at ${DATA_DIR}/webui.db. Reading DATABASE_URL and DATA_DIR from the
    same process environment keeps this correct if that ever changes, and
    fails loudly rather than guessing if the database stops being sqlite.

The token payload matches open_webui.utils.auth.create_token: an `id` claim
plus `jti` and `iat`, signed HS256 with the same secret decode_token uses.
"""
import sqlite3
import sys
import time
import uuid
from pathlib import Path

TOKEN_TTL_SECONDS = 300


def server_environment() -> dict[str, str]:
    """The environment of the process that holds WEBUI_SECRET_KEY.

    Every /proc entry is scanned rather than assuming the server is PID 1, so
    this keeps working under an init shim or a wrapper entrypoint.
    """
    for entry in sorted(Path("/proc").iterdir(), key=lambda p: p.name):
        if not entry.name.isdigit():
            continue
        try:
            raw = (entry / "environ").read_bytes()
        except OSError:
            continue
        found = {}
        for pair in raw.split(b"\0"):
            if not pair or b"=" not in pair:
                continue
            key, _, value = pair.partition(b"=")
            found[key.decode("utf-8", "replace")] = value.decode("utf-8", "replace")
        if found.get("WEBUI_SECRET_KEY"):
            return found
    raise SystemExit(
        "no running process exposes WEBUI_SECRET_KEY. Run this inside the "
        "open-webui container, while it is up."
    )


def sqlite_path(environment: dict[str, str]) -> Path:
    database_url = environment.get("DATABASE_URL", "").strip()
    if not database_url:
        # Mirrors open_webui.env: DATA_DIR defaults to BACKEND_DIR/data, which
        # is /app/backend/data in the published image. This repo's compose
        # overrides DATA_DIR to /data, so the env value is what normally wins;
        # the fallback keeps this correct against a stock container too.
        data_dir = environment.get("DATA_DIR", "/app/backend/data")
        return Path(data_dir) / "webui.db"
    if not database_url.startswith("sqlite:///"):
        raise SystemExit(
            "Open WebUI is not on sqlite (DATABASE_URL is set to a "
            f"{database_url.split(':', 1)[0]} URL). This script reads the "
            "admin account straight from the sqlite file; teach it the other "
            "backend before pointing a deploy at one."
        )
    # sqlite:////data/webui.db (four slashes, an absolute path) is what Open
    # WebUI builds from DATA_DIR. Stripping the three-slash scheme prefix
    # leaves /data/webui.db, and leaves a relative path relative.
    return Path(database_url[len("sqlite:///") :])


def first_admin_id(database: Path) -> str:
    if not database.exists():
        raise SystemExit(f"Open WebUI database not found at {database}")
    connection = sqlite3.connect(f"file:{database}?mode=ro", uri=True)
    try:
        row = connection.execute(
            'SELECT id FROM "user" WHERE role = ? ORDER BY created_at LIMIT 1',
            ("admin",),
        ).fetchone()
    finally:
        connection.close()
    if not row:
        raise SystemExit(
            "Open WebUI has no admin account yet, so the hive_jwt_forward "
            "Function cannot be installed. Sign in once as a tenant OWNER "
            "(which this deployment maps to an Open WebUI admin) and re-run "
            "the deploy."
        )
    return row[0]


def main() -> int:
    environment = server_environment()
    # Imported here, not at module scope: this file is piped into the
    # container's interpreter, and PyJWT only exists there.
    import jwt

    user_id = first_admin_id(sqlite_path(environment))
    now = int(time.time())
    token = jwt.encode(
        {
            "id": user_id,
            "jti": str(uuid.uuid4()),
            "iat": now,
            "exp": now + TOKEN_TTL_SECONDS,
        },
        environment["WEBUI_SECRET_KEY"],
        algorithm="HS256",
    )
    # PyJWT 1.x returned bytes; 2.x returns str. Normalize so the caller's
    # command substitution never captures a b'...' literal.
    if isinstance(token, bytes):
        token = token.decode()
    print(token)
    return 0


if __name__ == "__main__":
    # Nothing but the token may reach stdout: the caller captures it with a
    # command substitution. Every failure above raises SystemExit with a
    # message, which Python prints to stderr.
    sys.exit(main())
