#!/usr/bin/env python3
"""Self-check for the embedding-burst fix (issue #1609).

The defect, reproduced live on the demo box three times on 2026-08-31. Web
search fetched five real pages and then answered with no sources at all, and
the model told the user it had no live internet access. From the container log:

    Fetching pages: 5/5
    429, message='Too Many Requests', url='http://edge-api:8080/v1/embeddings'
    query_doc:result [[]] [[]]

Two separate faults produced that, and this file covers both.

SHAPE. Open WebUI already batches embedding calls and already has a
concurrency semaphore, in get_embedding_function (retrieval/utils.py). Both
knobs default to the wrong end of their range: RAG_EMBEDDING_BATCH_SIZE is 1,
so one HTTP request carries one chunk, and RAG_EMBEDDING_CONCURRENT_REQUESTS
is 0, which that function reads as "build no semaphore" and so fires every
request at once through asyncio.gather. Five pages chunk to tens of chunks at
the upstream CHUNK_SIZE of 1000 characters, so one search opened tens of
simultaneous POSTs against the gateway. The tests below run the REAL upstream
batching code, extracted from the vendored tree, against a counting stub, so
they measure what the deployment will actually do rather than a
reimplementation of it that could agree with a broken original.

SILENCE. process_web_search swallowed the resulting failure with
`except Exception as e: log.debug(...)` and still returned status True plus a
collection name nothing had been written to, which is why a total loss of
every source presented as a successful search. That half ships as
owui-patches/apply_web_search_embed_failure_1609_patch.py, exercised here
against a copy of the pinned file.

Structural, no framework, no network.
Run: python3 scripts/test_owui_embedding_burst.py
"""

import ast
import asyncio
import importlib.util
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
VENDORED_UTILS = REPO_ROOT / "vendor/open-webui/backend/open_webui/retrieval/utils.py"
VENDORED_RETRIEVAL = REPO_ROOT / "vendor/open-webui/backend/open_webui/routers/retrieval.py"
COMPOSE = REPO_ROOT / "deploy/docker/docker-compose.yml"
DOCKERFILE = REPO_ROOT / "deploy/docker/Dockerfile.open-webui"
PATCH = REPO_ROOT / "deploy/docker/owui-patches/apply_web_search_embed_failure_1609_patch.py"
MODULE_PATH = REPO_ROOT / "deploy/docker/owui-patches/hive_rag_env_config.py"

_spec = importlib.util.spec_from_file_location("hive_rag_env_config", MODULE_PATH)
hive_rag_env_config = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(hive_rag_env_config)

# Five fetched pages at the upstream CHUNK_SIZE of 1000 characters. Deliberately
# on the low side of what the box saw, so the assertions below hold for a
# thinner search too.
FIVE_PAGE_CHUNKS = 200


class _SilentLog:
    """Upstream's module logger, which the extracted function closes over."""

    def debug(self, *args, **kwargs):
        pass

    def info(self, *args, **kwargs):
        pass

    def warning(self, *args, **kwargs):
        pass

    def error(self, *args, **kwargs):
        pass


class Recorder:
    """A counting stand-in for one embeddings HTTP call.

    Records every batch it is handed and the high-water mark of simultaneous
    in-flight calls, which is the number the gateway's rate limit actually
    sees. The two awaits are what let asyncio.gather interleave: without them
    every coroutine would run start to finish before the next one began and
    the high-water mark would read 1 no matter what the code under test does.
    """

    def __init__(self):
        self.batches = []
        self.in_flight = 0
        self.max_in_flight = 0

    async def __call__(self, batch, prefix=None, user=None):
        self.batches.append(list(batch))
        self.in_flight += 1
        self.max_in_flight = max(self.max_in_flight, self.in_flight)
        await asyncio.sleep(0)
        await asyncio.sleep(0)
        self.in_flight -= 1
        return [[float(len(text))] for text in batch]

    @property
    def calls(self) -> int:
        return len(self.batches)


_PRELUDE = '''"""Generated by scripts/test_owui_embedding_burst.py. Not shipped."""
import asyncio


class _Log:
    def __getattr__(self, name):
        return lambda *args, **kwargs: None


log = _Log()
embedding_function = None
embedding_batch_size = 1
enable_async = True
concurrent_requests = 0
'''

_UPSTREAM = None


def _extract_upstream_source() -> str:
    """The real upstream async_embedding_function, lifted out verbatim.

    get_embedding_function defines two nested functions of that name, one per
    engine branch; the external-engine one (ollama, openai, azure_openai) is
    identified by the isinstance check that decides whether it has a list to
    batch. Lifting it into a module of its own turns every name it closed over
    into a module global, which is what makes the two knobs injectable without
    importing Open WebUI, whose dependency set is not installed here.

    Verbatim on purpose: the point is to measure what the shipped code does,
    not what a reimplementation of it would do. A reimplementation could agree
    with a broken original and this test would still pass.
    """
    source = VENDORED_UTILS.read_text()
    tree = ast.parse(source)
    candidates = [
        node
        for node in ast.walk(tree)
        if isinstance(node, ast.AsyncFunctionDef)
        and node.name == "async_embedding_function"
        and "isinstance" in ast.dump(node)
    ]
    assert len(candidates) == 1, (
        "expected exactly one external-engine async_embedding_function in "
        f"{VENDORED_UTILS.name}, found {len(candidates)}. Upstream shifted; "
        "this test needs updating, not deleting"
    )
    node = candidates[0]
    segment = ast.get_source_segment(source, node)
    assert segment, "could not recover the function source"
    lines = segment.splitlines()
    indent = node.col_offset
    flattened = [lines[0]] + [
        line[indent:] if not line[:indent].strip() else line for line in lines[1:]
    ]
    return _PRELUDE + "\n\n" + "\n".join(flattened) + "\n"


def _upstream_module():
    global _UPSTREAM
    if _UPSTREAM is None:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "upstream_batcher.py"
            path.write_text(_extract_upstream_source())
            spec = importlib.util.spec_from_file_location("upstream_batcher", path)
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)
        _UPSTREAM = module
    return _UPSTREAM


def _embed(chunks, batch_size, concurrent_requests):
    """Run the real batcher over chunks with the given knobs."""
    module = _upstream_module()
    recorder = Recorder()
    module.embedding_function = recorder
    module.embedding_batch_size = batch_size
    module.concurrent_requests = concurrent_requests
    module.enable_async = True
    embeddings = asyncio.run(
        module.async_embedding_function(chunks, prefix=None, user=None)
    )
    return recorder, embeddings


def _chunks(count):
    return [f"chunk {index} " + "x" * 985 for index in range(count)]


def _compose_service_block(service: str) -> str:
    """The text of one compose service, from its own key to the next one.

    Same helper as scripts/test_owui_rag_env_config.py, and for the same
    reason: service keys sit at exactly two spaces of indentation and nothing
    else in that file does, so asserting against one service is the difference
    between a guard and a word count. Copied rather than imported because that
    file is a test, not a library.
    """
    match = re.search(
        rf"^  {re.escape(service)}:$(.*?)(?=^  [a-z0-9][a-z0-9._-]*:$|\Z)",
        COMPOSE.read_text(),
        re.S | re.M,
    )
    assert match, f"docker-compose.yml has no service named {service!r}"
    return match.group(1)


def _compose_default(variable: str) -> int:
    """The integer default compose interpolates for a variable on open-webui."""
    block = _compose_service_block("open-webui")
    match = re.search(
        rf"^      {re.escape(variable)}: \$\{{{re.escape(variable)}:-(\d+)\}}$",
        block,
        re.M,
    )
    assert match, (
        f"docker-compose.yml's open-webui service does not set {variable} with "
        f"an integer default. Issue #1609: unset means upstream's own default, "
        f"which is the unbatched, unbounded shape that took web search down."
    )
    return int(match.group(1))


def test_the_upstream_defaults_are_the_burst() -> None:
    """The control, and the reason this file exists.

    Batch size 1 with no concurrency bound is what the deployment ran on
    2026-08-31: one request per chunk, every one of them in flight at the same
    time. Pinned as a measurement rather than described, so nobody has to take
    the issue's word for the shape.
    """
    recorder, embeddings = _embed(_chunks(FIVE_PAGE_CHUNKS), 1, 0)
    assert recorder.calls == FIVE_PAGE_CHUNKS, recorder.calls
    assert recorder.max_in_flight == FIVE_PAGE_CHUNKS, recorder.max_in_flight
    assert len(embeddings) == FIVE_PAGE_CHUNKS


def test_a_five_page_search_is_a_handful_of_requests() -> None:
    """The fix, measured through the real batcher with the shipped compose
    defaults: a five page search stops being tens of requests."""
    batch_size = _compose_default("RAG_EMBEDDING_BATCH_SIZE")
    concurrency = _compose_default("RAG_EMBEDDING_CONCURRENT_REQUESTS")
    recorder, embeddings = _embed(_chunks(FIVE_PAGE_CHUNKS), batch_size, concurrency)

    expected_calls = -(-FIVE_PAGE_CHUNKS // batch_size)  # ceiling division
    assert recorder.calls == expected_calls, recorder.calls
    assert recorder.calls <= 4, (
        f"{FIVE_PAGE_CHUNKS} chunks still cost {recorder.calls} requests at "
        f"batch size {batch_size}; issue #1609 is about the request COUNT, so "
        f"a batch size that leaves tens of them has not fixed anything"
    )
    assert len(embeddings) == FIVE_PAGE_CHUNKS


def test_the_concurrency_bound_is_what_holds_for_a_larger_document() -> None:
    """Batching alone would leave the same burst one document size away.

    Fifty times the chunk count of a five page search, which a single uploaded
    PDF reaches easily. The request count rises, as it must; the number in
    flight at once does not, which is the number the gateway's limit sees.
    """
    batch_size = _compose_default("RAG_EMBEDDING_BATCH_SIZE")
    concurrency = _compose_default("RAG_EMBEDDING_CONCURRENT_REQUESTS")
    recorder, embeddings = _embed(_chunks(FIVE_PAGE_CHUNKS * 50), batch_size, concurrency)

    assert recorder.calls > 4, "the larger document must not fit in one batch"
    assert recorder.max_in_flight <= concurrency, (
        f"{recorder.max_in_flight} embedding requests were in flight at once "
        f"with the bound set to {concurrency}: a larger document still "
        f"recreates the burst issue #1609 is about"
    )
    # The assertion above only proves the semaphore is obeyed, which stays true
    # for any bound at all, so on its own it would pass with the compose
    # default raised to 200 and the original defect back. This one is absolute:
    # roughly 200 in flight is what took web search down, and the bound is per
    # document (see the compose comment), so anything above a handful is not a
    # bound worth having. Deliberately a ceiling rather than an equality check
    # on 4, so tuning the value stays possible without editing a test, while
    # tuning it back into a burst does not.
    assert recorder.max_in_flight <= 10, (
        f"the shipped concurrency default is {concurrency}, which let "
        f"{recorder.max_in_flight} requests run at once; issue #1609 was ~200 "
        f"in flight, and this bound is per document, so a default this high is "
        f"not a bound"
    )
    assert len(embeddings) == FIVE_PAGE_CHUNKS * 50


def test_batching_preserves_chunk_order() -> None:
    """The vectors are indexed positionally against texts in
    save_docs_to_vector_db, so a reordering would attach every chunk's vector
    to a different chunk's text and corrupt retrieval silently."""
    chunks = _chunks(37)
    recorder, embeddings = _embed(chunks, 10, 2)
    assert [text for batch in recorder.batches for text in batch] == chunks
    assert embeddings == [[float(len(text))] for text in chunks]


def test_both_knobs_are_reconciled_from_the_environment() -> None:
    """Compose alone cannot move either value on a volume that has already
    booted: both are persisted config, seeded once and thereafter read from
    Open WebUI's own database. The demo box booted long before either variable
    appeared in compose, so without this it keeps 1 and 0 forever."""
    applied = hive_rag_env_config.overrides(
        dict(RAG_EMBEDDING_BATCH_SIZE="100", RAG_EMBEDDING_CONCURRENT_REQUESTS="4")
    )
    assert applied["rag.embedding_batch_size"] == 100, applied
    assert applied["rag.embedding_concurrent_requests"] == 4, applied


def test_both_are_persisted_as_integers_not_strings() -> None:
    """A persisted string reaches a slice bound and a semaphore size, both of
    which raise TypeError at request time rather than being ignored."""
    applied = hive_rag_env_config.overrides(
        dict(RAG_EMBEDDING_BATCH_SIZE=" 64 ", RAG_EMBEDDING_CONCURRENT_REQUESTS="2")
    )
    assert isinstance(applied["rag.embedding_batch_size"], int)
    assert isinstance(applied["rag.embedding_concurrent_requests"], int)
    assert applied["rag.embedding_batch_size"] == 64


def _refused(environ) -> bool:
    try:
        hive_rag_env_config.overrides(environ)
    except RuntimeError:
        return True
    return False


def test_zero_is_refused_rather_than_obeyed() -> None:
    """Zero parses as an integer and means two different broken things: a
    batch size of 0 makes every embedding call raise, and a concurrency of 0
    means no bound at all, which is this issue. Unbounded by accident is the
    dangerous direction, so the boot refuses."""
    assert _refused(dict(RAG_EMBEDDING_BATCH_SIZE="0"))
    assert _refused(dict(RAG_EMBEDDING_CONCURRENT_REQUESTS="0"))


def test_a_malformed_value_is_refused() -> None:
    for value in ("four", "-1", "1.5", "১০০"):
        assert _refused(dict(RAG_EMBEDDING_BATCH_SIZE=value)), value


def test_unset_leaves_the_persisted_values_alone() -> None:
    applied = hive_rag_env_config.overrides(
        dict(RAG_EMBEDDING_BATCH_SIZE="", RAG_EMBEDDING_CONCURRENT_REQUESTS="  ")
    )
    assert "rag.embedding_batch_size" not in applied
    assert "rag.embedding_concurrent_requests" not in applied


def _apply_patch_to_a_copy(dest_dir: Path):
    """Run the real build-time patch against a copy of the pinned file."""
    dest = dest_dir / "retrieval.py"
    shutil.copy(VENDORED_RETRIEVAL, dest)
    env = dict(os.environ)
    env["HIVE_OWUI_RETRIEVAL_PY"] = str(dest)
    result = subprocess.run(
        [sys.executable, str(PATCH)], env=env, capture_output=True, text=True
    )
    return result, dest


def test_the_patch_removes_the_silent_swallow() -> None:
    """The silence half of #1609. process_web_search swallowed the
    save_docs_to_vector_db failure into log.debug and still returned status
    True with a collection name nothing had been written to, so a search that
    dropped all five of its fetched pages was reported as a completed one."""
    with tempfile.TemporaryDirectory() as tmp:
        result, dest = _apply_patch_to_a_copy(Path(tmp))
        assert result.returncode == 0, result.stdout + result.stderr
        patched = dest.read_text()

        assert "error saving docs" not in patched, "the swallow is still there"
        assert patched.count("# hive (#1609)") == 1, "marker count drifted"
        assert "log.exception(" in patched
        assert "HTTP_502_BAD_GATEWAY" in patched
        ast.parse(patched)


def test_the_patch_leaks_no_internal_address_to_the_client() -> None:
    """The raised detail is written here, not borrowed from the exception.

    aiohttp bakes the request URL into its own string, so re-raising the
    original would publish an internal compose address to the signed-in user
    through the enclosing handler, which is exactly the leak
    apply_audio_error_leak_patch.py exists to close (#1562).
    """
    with tempfile.TemporaryDirectory() as tmp:
        result, dest = _apply_patch_to_a_copy(Path(tmp))
        assert result.returncode == 0, result.stdout + result.stderr
        tree = ast.parse(dest.read_text())

        details = []
        for node in ast.walk(tree):
            if not isinstance(node, ast.Raise) or not isinstance(node.exc, ast.Call):
                continue
            for keyword in node.exc.keywords:
                if keyword.arg == "detail" and isinstance(keyword.value, ast.Constant):
                    details.append(keyword.value.value)

        hive_details = [text for text in details if "could not index" in str(text)]
        assert len(hive_details) == 1, hive_details
        for host in ("edge-api", "control-plane", "litellm", "open-webui", "8080"):
            assert host not in hive_details[0], hive_details[0]


def test_the_patch_is_wired_into_the_image() -> None:
    """A patch script that no Dockerfile stage runs is inert, which is the
    trap this repo hits most often on Open WebUI backend changes."""
    dockerfile = DOCKERFILE.read_text()
    assert "apply_web_search_embed_failure_1609_patch.py" in dockerfile
    assert "grep -c '# hive (#1609)'" in dockerfile, (
        "the Dockerfile must assert the marker count, so a patch that silently "
        "becomes a no-op fails the build instead of shipping the swallow back"
    )
    assert "! grep -q 'error saving docs'" in dockerfile


# The three literals every measurement in this file rests on. They live in
# upstream's get_embedding_function, which this fix configures rather than
# patches, so nothing else in the build would notice if they moved.
BATCHER_LITERALS = (
    "if concurrent_requests:",
    "asyncio.Semaphore(concurrent_requests)",
    "range(0, len(query), embedding_batch_size)",
)


def test_the_image_is_bound_to_the_batcher_this_file_measures() -> None:
    """The one drift path the marker greps above do not cover.

    The shape half of #1609 patches nothing: the batching and the semaphore
    are upstream's own and the fix is only that the two knobs stop sitting at
    1 and 0. So the tests here measure the VENDORED copy of
    get_embedding_function while the container runs the pinned image's copy,
    and a digest bump inside the same tag that reshuffled that function would
    leave every assertion in this file green over code the deployment no
    longer runs. The Dockerfile greps for the same literals at build time, so
    that drift fails the image build instead of passing silently here.
    """
    dockerfile = DOCKERFILE.read_text()
    vendored = VENDORED_UTILS.read_text()
    for literal in BATCHER_LITERALS:
        assert literal in vendored, (
            f"{literal!r} is gone from the vendored batcher, so the tests in "
            f"this file no longer measure what they claim to"
        )
        assert literal in dockerfile, (
            f"the Dockerfile must grep {literal!r} in retrieval/utils.py, or "
            f"nothing binds the running image's batcher to the vendored copy "
            f"measured here"
        )


def test_env_example_documents_both_knobs() -> None:
    text = (REPO_ROOT / ".env.example").read_text()
    for variable in ("RAG_EMBEDDING_BATCH_SIZE", "RAG_EMBEDDING_CONCURRENT_REQUESTS"):
        assert re.search(rf"^{variable}=\d+$", text, re.M), variable


def main() -> None:
    for name, fn in sorted(globals().items()):
        if name.startswith("test_") and callable(fn):
            fn()
    print("ok: owui embedding burst shape and loud indexing failure (issue #1609)")


if __name__ == "__main__":
    sys.exit(main())
